### ISSUE TITLE
quickstart

### ISSUE THREAD

**Issue by benjyz** [jcburley/joker#22]
to make the quickstart work I had to

1. set ```export GO111MODULE=off```

2. replace git co gostd  with git checkout gostd

3. then I get:
```
./run.sh
# github.com/candid82/joker/core
./g_goswitch.go:8:20: undefined: GoTypeInfo
core/object.go:3: running "go": exit status

```

**Comment by jcburley** [comment]
> to make the quickstart work I had to
> 
> 1. set `export GO111MODULE=off`

I couldn't reproduce any issue on my Ubuntu machine running go 1.17 with `export Go111MODULE=on`; what version of go are you using (>= 1.16 is now documented as required)?

If the problem persists, could you post a gist showing the build session and whatever else might help me track this down?

> 2. replace git co gostd  with git checkout gostd

Fixed `README.md`, thanks!

> 3. then I get:
> 
> ```
> ./run.sh
> # github.com/candid82/joker/core
> ./g_goswitch.go:8:20: undefined: GoTypeInfo
> core/object.go:3: running "go": exit status
> ```

Ooh, I forgot to change the template for that file, after changing how it's autogenerated by `gostd`, because I build with `joker-good` symlinked to a "good" version to speed up my builds...sorry!

Fixed.

Thanks for trying this out!!

**Comment by benjyz** [comment]
> > to make the quickstart work I had to
> > 
> > 1. set `export GO111MODULE=off`
> 
> I couldn't reproduce any issue on my Ubuntu machine running go 1.17 with `export Go111MODULE=on`; what version of go are you using (>= 1.16 is now documented as required)?

go version
go version go1.16.5 darwin/amd64

> 
> If the problem persists, could you post a gist showing the build session and whatever else might help me track this down?
> 
> > 1. replace git co gostd  with git checkout gostd
> 
> Fixed `README.md`, thanks!
> 
> > 1. then I get:
> > 
> > ```
> > ./run.sh
> > # github.com/candid82/joker/core
> > ./g_goswitch.go:8:20: undefined: GoTypeInfo
> > core/object.go:3: running "go": exit status
> > ```
> 
> Ooh, I forgot to change the template for that file, after changing how it's autogenerated by `gostd`, because I build with `joker-good` symlinked to a "good" version to speed up my builds...sorry!
> 
> Fixed.
> 
> Thanks for trying this out!!

works!
